### ISSUE TITLE
Only webp images gets variants generated

### ISSUE THREAD

**Issue by erikw** [pcouy/jekyll-picture-tag-ng#2]
Using the default config from the [README](https://github.com/pcouy/jekyll-picture-tag-ng#configuration) and a Jekyll site with a bunch of jpg,png and webp images in `assets/images`, the plugin only generates variants for the webp images I have.

As I understand the README, any jpg/png/webp would autmoatically gets variants generated of different sizes and formats. More specifically I'm looking to have my jpg/png images to get automatic webp variants generated an inserted to the generated HTML with the `<picture>` tag.

^ did I understand it correct how the plugins should work? If so, is there some configuration that I would need to change from the default to get this? :)

**Comment by pcouy** [comment]
The plugin should generate variants for files with names ending with `.jpg`, `.jpeg` and `.webp` (see [these search results](https://github.com/search?q=repo%3Apcouy%2Fjekyll-picture-tag-ng+jpeg&type=code)). It is expected that `png` files won't get converted, as the use case for this format is very different from using `jpeg`/`webp`. 

**Can you confirm that `jpg` source images do not get converted by the plugin, or is it only happening with `png` files ?**

##### More details on why this plugin does not handle conversion from `png` files

> Portable Network Graphics files (PNGs) are compressible and like JPEGS, can handle 16 million colors. They’re mostly used for web graphics, logos, charts, and illustrations, rather than high-quality photographs, because they take up more storage space than JPEGs. One thing PNGs offer that JPEGs don’t is the ability to handle graphics with transparent backgrounds.
>
> -- [Adobe comparison of JPEG vs PNG](https://www.adobe.com/creativecloud/file-types/image/comparison/jpeg-vs-png.html)

Conversion between jpeg and png usually does not produce great results (visible compression artifacts when going from png to jpeg ; larger file sizes when going from jpeg to png). You should provide your images in the right formats depending of their types.

webp and jpeg use cases are very similar : they are both used for lossy compression of photographs. Webp tries to be some kind of sucessor to jpeg, with higher compression rates and the added benefit of handling transparency. However, not all browsers (especially older ones) support webp. 

The goal of this plugin is to let browsers pick the best variant based on screen-size and webp support in order to optimize loading times. It also handles adding an uniform background when converting webp that use transparency to jpeg, which allows to emulate transparency in photographs for browsers that do not support webp.

On the other hand, as long as you work with web graphics, logos, charts, and illustrations, PNG is better than JPEG/WEBP at producing small files that support transparency.

**Comment by erikw** [comment]
> Can you confirm that `jpg` source images do not get converted by the plugin, or is it only happening with `png` files ?

My bad! :ashamed: For this site, there was actually only webp and png images. I dropped in a jpg and it is also converted correctly like the webp ones.

Thanks for the explanation and background of PNG :)
